# Site settings
title: "Joel Medeiros"
email: "jooelmedeiros+blog@gmail.com"
description: "A passionate about innovation, technology and agile teams that seeks to learn everyday how technology could impact people lives."
baseurl: ""
url: "http://joelmedeiros.github.io"
title_description: "A passionate about innovation, technology and agile teams that seeks to learn everyday how technology could impact people lives."
title_image: "https://www.gravatar.com/avatar/96993a1727148b81021e029851f52029?s=500&d=mm"
google_analytics: "UA-162037854-1"
github_repository: https://github.com/joelmedeiros
addthis_id:
post_limit: 5

# Social usernames/URLs
twitter_username: _joelmedeiros
github_username:  joelmedeiros
linkedin_link: http://linkedin.com/in/joelmedeiros
speaker_deck: joelmedeiros

# Footer
footer_left:
footer_right:

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
